export default {
  login: "fercopp",
  id: 40127419,
  node_id: "MDQ6VXNlcjQwMTI3NDE5",
  avatar_url: "https://avatars.githubusercontent.com/u/40127419?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/fercopp",
  html_url: "https://github.com/fercopp",
  followers_url: "https://api.github.com/users/fercopp/followers",
  following_url: "https://api.github.com/users/fercopp/following{/other_user}",
  gists_url: "https://api.github.com/users/fercopp/gists{/gist_id}",
  starred_url: "https://api.github.com/users/fercopp/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/fercopp/subscriptions",
  organizations_url: "https://api.github.com/users/fercopp/orgs",
  repos_url: "https://api.github.com/users/fercopp/repos",
  events_url: "https://api.github.com/users/fercopp/events{/privacy}",
  received_events_url: "https://api.github.com/users/fercopp/received_events",
  type: "User",
  site_admin: false,
  name: "Fercopp",
  company: null,
  blog: "",
  location: "México",
  email: null,
  hireable: null,
  bio: "Software Engineer Student",
  twitter_username: null,
  public_repos: 3,
  public_gists: 0,
  followers: 1,
  following: 3,
  created_at: "2018-06-09T20:25:49Z",
  updated_at: "2022-03-15T02:23:09Z",
};
