export default [
  {
    login: "IrvinSanchezQ",
    id: 78123620,
    node_id: "MDQ6VXNlcjc4MTIzNjIw",
    avatar_url: "https://avatars.githubusercontent.com/u/78123620?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/IrvinSanchezQ",
    html_url: "https://github.com/IrvinSanchezQ",
    followers_url: "https://api.github.com/users/IrvinSanchezQ/followers",
    following_url:
      "https://api.github.com/users/IrvinSanchezQ/following{/other_user}",
    gists_url: "https://api.github.com/users/IrvinSanchezQ/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/IrvinSanchezQ/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/IrvinSanchezQ/subscriptions",
    organizations_url: "https://api.github.com/users/IrvinSanchezQ/orgs",
    repos_url: "https://api.github.com/users/IrvinSanchezQ/repos",
    events_url: "https://api.github.com/users/IrvinSanchezQ/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/IrvinSanchezQ/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Omargn",
    id: 83617317,
    node_id: "MDQ6VXNlcjgzNjE3MzE3",
    avatar_url: "https://avatars.githubusercontent.com/u/83617317?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Omargn",
    html_url: "https://github.com/Omargn",
    followers_url: "https://api.github.com/users/Omargn/followers",
    following_url: "https://api.github.com/users/Omargn/following{/other_user}",
    gists_url: "https://api.github.com/users/Omargn/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Omargn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Omargn/subscriptions",
    organizations_url: "https://api.github.com/users/Omargn/orgs",
    repos_url: "https://api.github.com/users/Omargn/repos",
    events_url: "https://api.github.com/users/Omargn/events{/privacy}",
    received_events_url: "https://api.github.com/users/Omargn/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "FerIbarra1",
    id: 97769653,
    node_id: "U_kgDOBdPYtQ",
    avatar_url: "https://avatars.githubusercontent.com/u/97769653?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/FerIbarra1",
    html_url: "https://github.com/FerIbarra1",
    followers_url: "https://api.github.com/users/FerIbarra1/followers",
    following_url:
      "https://api.github.com/users/FerIbarra1/following{/other_user}",
    gists_url: "https://api.github.com/users/FerIbarra1/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/FerIbarra1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/FerIbarra1/subscriptions",
    organizations_url: "https://api.github.com/users/FerIbarra1/orgs",
    repos_url: "https://api.github.com/users/FerIbarra1/repos",
    events_url: "https://api.github.com/users/FerIbarra1/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/FerIbarra1/received_events",
    type: "User",
    site_admin: false,
  },
];
